### ISSUE TITLE
Confusion about data units

### ISSUE THREAD

**Issue by ghost** [cran/digitalDLSorteR#1]
Hi DigitalDLSorter team，
I am very interested in your DigitalDLSorter, this idea deeply attracted me. When I read your paper and github code, I have two confusion and need to consult you. 
(1) Your article mentions converting TCGA data to tpm as the data unit, but in your code description it mentions cpm, whether you are using cpm or tpm.
(2) I think the dimensions of bulk data and single-cell data are different. How do you ensure that your integrated pseudo-bulk expression profile is in the same order of magnitude as the real bulk data expression profile?

![image](https://user-images.githubusercontent.com/75767091/139576561-46428c37-5ef7-48a7-8e5d-02065e7351bd.png)

![image](https://user-images.githubusercontent.com/75767091/139576215-33338cbf-48c1-40b6-ab94-ee86439ebcdb.png)

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by ghost** [comment]
Thanks!
